name: CI/CD Backend

on:
  push:
    branches:
      - test/vps-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: 22
          script: |
            cd /SGU-Backend
            git pull origin
            docker-compose pull
            docker-compose up -d
